# Generated by Django 3.2.5 on 2022-04-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='price',
            new_name='purchased_price',
        ),
    ]
